version: '3'
services:
  node-app:
    build: .
    environment:
      - REDIS_HOST=redis-server
      - EXPRESS_PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - .:/var/www/app
  redis-server:
    image: 'redis'